### ISSUE TITLE
Open Graph and Twitter metadata

### ISSUE THREAD

**Issue by chriscroome** [fiqus/coophub#57]
I'd be interested in seeing if some additional Open Graph and Twitter metadata could be added to `<head>` sections of pages, see:

* [The Open Graph protocol](http://ogp.me/)
* [Facebook: A Guide to Sharing for Webmasters](https://developers.facebook.com/docs/sharing/webmasters)
* [Optimize Tweets with Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards)
* [Twitter Card Validator](https://cards-dev.twitter.com/validator)

Is this the only template for the HTML head?

* [lib/coophub_web/templates/layout/app.html.eex](https://github.com/fiqus/coophub/blob/master/lib/coophub_web/templates/layout/app.html.eex)

**Comment by diegomanuel** [comment]
> Is this the only template for the HTML head?

Yes, and note that it will **not** change from page to page.
We discussed a little bit with @pbrudnick to make that `<head>` dynamic because right now all the page navigation/behaviour is handled by JS (the backend returns always the same base/default html content) so pages like https://coophub.io/languages/elixir will have the same header as home.

We will probably create a new issue for that!

**Comment by pbrudnick** [comment]
Sorry, I think we still need to add the twitter-related metatags

**Comment by chriscroome** [comment]
A simple test is to put a URL into a comment, on a line on it's own, no white space at the start, on [a Discourse site](https://patio.ica.coop/) and if generates a [onebox](https://github.com/discourse/onebox) then the metadata is working, the same goes for a tweet, but that can be an annoying way to test things if you have any followers :wink:.
